spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bwood3/configuration-files.git
          username: ${git.username}
          password: ${git.token}
          default-label: main

server:
  port: 8071



