spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/bwood3/configuration-files.git
          username: ${git.username}
          password: ${git.token}
          default-label: master

server:
  port: 8071



